name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Create zip
        run: |
          mkdir -p out
          cd ..
          zip -r Chattynator/out/Chattynator.zip Chattynator/ \
            --exclude "Chattynator/.git/*" \
            --exclude "Chattynator/.github/*" \
            --exclude "Chattynator/out/*"

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: out/Chattynator.zip
