name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: |
          mkdir -p out
          zip -r out/Chattynator.zip . \
            --exclude "*.git*" \
            --exclude ".github/*" \
            --exclude "out/*"

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: out/Chattynator.zip
